"""followers

Revision ID: 071fbc0dba9e
Revises: 9ed32b05b040
Create Date: 2018-04-24 14:37:52.102577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071fbc0dba9e'
down_revision = '9ed32b05b040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
