"""empty message

Revision ID: 4206a8775267
Revises: 96bfa57aaa4e
Create Date: 2018-05-02 15:36:15.478704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4206a8775267'
down_revision = '96bfa57aaa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar1', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
