"""empty message

Revision ID: 96bfa57aaa4e
Revises: 07275b360344
Create Date: 2018-05-02 15:34:27.674313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bfa57aaa4e'
down_revision = '07275b360344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar1', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar1')
    # ### end Alembic commands ###
